In [1]:
from os import environ, makedirs, path

import pandas as pd
from dotenv import load_dotenv
from unidecode import unidecode

In [2]:
load_dotenv()

True

# Atualização de 2026 - Mortalidade Materna e Mortalidade Infantil

Para o ano de 2026, o GT Saúde decidiu adicionar dois painéis com dados específicos de mortalidade, um para mortalidade materna e outro para mortalidade infantil. Esses temas já haviam sido sugeridos pelos especialistas que participaram em 2025, e também foram trabalhados pela auditoria do TCMSP, resultando inclusive em um evento em parceria com o OPP no ano de 2026.

Agora, precisamos adicionar esses dados padronizados no formato adequado ao Qlik Sense para que sejam incorporados ao DataSP.

Os dados são coeficientes semelhantes ao de mortalidade geral, mas com recortes específicos. De todo modo, tratam-se de coeficientes ponderados. No caso de mortalidade materna, temos o seguinte coeficiente:

$$ \text{Razão de mortalidade materna} = \frac{\text{Número de óbitos de mulheres por causas e condições consideradas de morte materna}}{\text{Número de nascidos vivos}} \times 100.000 $$

E, no caso de mortalidade infantil, temos:

$$ \text{Taxa de mortalidade infantil} = \frac{\text{Número de óbitos menores de 1 ano de idade}}{\text{Número de nascidos vivos}} \times 1.000 $$

Para que possamos recalcular esses indicadores de acordo com a seleção de Subprefeituras feito dinamicamente pelo usuário, precisamos obter o numerador e o denomidador deles e agregá-los dinamicamente de acordo com a seleção.

Para isso, existem duas alternativas possíveis. Uma delas é obter a razão (ou taxa) de mortalidade já calculada para cada Subprefeitura e estimar o número de óbitos com base no número de nascidos vivos. Outra forma seria obter os componentes da razão (taxa) e calculá-lo para cada Subprefeitura. A primeira maneira é preferida, porque garante que os indicadores reflitam exatamente os valores disponíveis em bases de dados oficiais. Entretanto, esses valores existem apenas para o ano de 2024. Para o ano de 2025, estão disponíveis apenas dados provisórios de mortalidade geral, de modo que o cálculo da razão (taxa) é possível de modo provisório, ainda que não esteja disponível em bases oficiais.

Portanto, as duas maneiras serão utilizadas: para o ano de 2024, serão utilizados os valores diponíveis em bases oficiais e o número de óbitos será estimado com base no número de nascidos vivos; para o ano de 2025, a razão (taxa) será calculada com base nos dados de mortalidade geral e nascidos vivos.

# Extração dos dados

## Mortalidade Materna

Esta razão será obtida do ObservaSampa, mas o download está apresentando um erro no momento. Os dados foram extraídos e corrigidos manualmente e estão disponíveis na pasta de dados do projeto

### 2024

In [3]:
data_input_dir = path.join('data', 'input', 'saude')

In [4]:
file_name_materna = 'mortalidade_materna_2024.csv'
df_materna_24 = pd.read_csv(path.join(data_input_dir, file_name_materna), sep=';', encoding='latin1', decimal=',')
df_materna_24

,região,nivel_regional,indicador,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,São Paulo,Município,03.01.01 Razão de mortalidade materna (por 100...,59.5049,49.4625,49.1477,62.5654,58.4294,56.7917,59.0706,47.7766,50.4430,56.4131,65.0961,35.5896,29.5247,25.6544
1,Guaianases,Subprefeitura,03.01.01 Razão de mortalidade materna (por 100...,120.6030,39.8248,138.5864,153.6393,118.8119,59.8563,155.6723,60.9632,63.5997,45.1365,0.0000,0.0000,79.7448,56.9638
2,Ipiranga,Subprefeitura,03.01.01 Razão de mortalidade materna (por 100...,15.1883,76.4292,15.2999,30.1114,44.6163,77.9180,15.7978,15.5933,16.7898,35.6888,58.3771,0.0000,41.0256,21.5936
3,Pinheiros,Subprefeitura,03.01.01 Razão de mortalidade materna (por 100...,96.3391,32.4044,33.0251,32.4570,0.0000,34.3525,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,Pirituba-Jaraguá,Subprefeitura,03.01.01 Razão de mortalidade materna (por 100...,42.3430,57.6037,29.5639,43.3839,72.1605,77.1724,76.2544,31.5657,64.9351,88.9363,55.5042,56.9801,37.6152,20.3707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,Vila Guilherme,Distrito,03.01.01 Razão de mortalidade materna (por 100...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,446.4286,0.0000,153.6098,0.0000
125,Vila Matilde,Distrito,03.01.01 Razão de mortalidade materna (por 100...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,203.6660,99.2063,104.4932,109.0513
126,Vila Prudente,Distrito,03.01.01 Razão de mortalidade materna (por 100...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,90.4977,0.0000,0.0000,0.0000
127,Penha,Distrito,03.01.01 Razão de mortalidade materna (por 100...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,79.4913
128,São Miguel,Distrito,03.01.01 Razão de mortalidade materna (por 100...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,95.1475,97.3710,99.2063,104.7120

### 2025

Para 2025, obteremos os dados de mortalidade geral filtrando para mulheres com causas relacionadas ao Capítulo XV. Gravidez parto e puerpério do CID10. Esses dados também são extraídos manualmente, desta vez do TabNet, e adicionados a pasta de dados deste projeto.

In [5]:
file_name_obitos_materna_25 = 'A002518192_29_143_95.csv'
df_obitos_materna_25 = pd.read_csv(path.join(data_input_dir, file_name_obitos_materna_25),
                                   sep=';', encoding='latin1', decimal=',', skiprows=5)
df_obitos_materna_25

                             Subprefeitura residência Óbitos_Residentes_MSP
0                           Aricanduva/Formosa/Carrão                     2
1                                             Butantã                     1
2                                         Campo Limpo                     1
3                                   Capela do Socorro                     3
4                             Casa Verde/Cachoeirinha                     -
5                                       Cidade Ademar                     2
6                                   Cidade Tiradentes                     -
7                                  Ermelino Matarazzo                     -
8                               Freguesia/Brasilândia                     -
9                                          Guaianases                     1
10                                           Ipiranga                     2
11                                     Itaim Paulista                     4
12                                           Itaquera                     3
13                                          Jabaquara                     -
14                                    Jaçanã/Tremembé                     3
15                                               Lapa                     -
16                                        M'Boi Mirim                     1
17                                              Mooca                     3
18                                        Parelheiros                     -
19                                              Penha                     2
20                                              Perus                     2
21                                          Pinheiros                     -
22                                           Pirituba                     2
23                                   Santana/Tucuruvi                     1
24                                        Santo Amaro                     1
25                                         São Mateus                     3
26                                         São Miguel                     2
27                                          Sapopemba                     2
28                                                 Sé                     1
29                          Vila Maria/Vila Guilherme                     3
30                                       Vila Mariana                     -
31                                      Vila Prudente                     -
32                                           Ignorado                     1
33                                              Total                    46
34  Fonte: Sistema de Informações sobre Mortalidad...                   NaN
35                                             Notas:                   NaN
36  1. Para tabulações de proporções, o campo refe...                   NaN
37  2. A partir de 2005, os óbitos por acidentes d...                   NaN
38    3. Dados provisórios. Atualizado em 23/10/2026.                   NaN

Vamos remover as linhas finais com informações complementares sobre os dados

In [6]:
df_obitos_materna_25 = df_obitos_materna_25[:-6]
df_obitos_materna_25

     Subprefeitura residência Óbitos_Residentes_MSP
0   Aricanduva/Formosa/Carrão                     2
1                     Butantã                     1
2                 Campo Limpo                     1
3           Capela do Socorro                     3
4     Casa Verde/Cachoeirinha                     -
5               Cidade Ademar                     2
6           Cidade Tiradentes                     -
7          Ermelino Matarazzo                     -
8       Freguesia/Brasilândia                     -
9                  Guaianases                     1
10                   Ipiranga                     2
11             Itaim Paulista                     4
12                   Itaquera                     3
13                  Jabaquara                     -
14            Jaçanã/Tremembé                     3
15                       Lapa                     -
16                M'Boi Mirim                     1
17                      Mooca                     3
18                Parelheiros                     -
19                      Penha                     2
20                      Perus                     2
21                  Pinheiros                     -
22                   Pirituba                     2
23           Santana/Tucuruvi                     1
24                Santo Amaro                     1
25                 São Mateus                     3
26                 São Miguel                     2
27                  Sapopemba                     2
28                         Sé                     1
29  Vila Maria/Vila Guilherme                     3
30               Vila Mariana                     -
31              Vila Prudente                     -
32                   Ignorado                     1

## Mortalidade Infantil

### 2024

Neste caso, tanto a taxa, quanto os dados provisórios de óbitos serão obtidos do TabNet. Vamos começar pela taxa de mortalidade infantil.

In [7]:
file_name_infantil_24 = 'A003317192_29_141_165.csv'
df_infantil_24 = pd.read_csv(path.join(data_input_dir, file_name_infantil_24),
                                         sep=';', encoding='latin1', decimal=',', skiprows=3)
df_infantil_24

                                  Subprefeitura resid  Coef_mort_infantil
0                           Aricanduva/Formosa/Carrão               11.94
1                                             Butantã                8.41
2                                         Campo Limpo               10.25
3                                   Capela do Socorro               12.97
4                             Casa Verde/Cachoeirinha               11.43
5                                       Cidade Ademar               11.77
6                                   Cidade Tiradentes                9.01
7                                  Ermelino Matarazzo                8.26
8                               Freguesia/Brasilândia               15.18
9                                          Guaianases               13.96
10                                           Ipiranga               10.58
11                                     Itaim Paulista               12.11
12                                           Itaquera               12.19
13                                          Jabaquara                9.37
14                                    Jaçanã/Tremembé               12.24
15                                               Lapa                3.50
16                                        M'Boi Mirim               10.21
17                                              Mooca               11.56
18                                        Parelheiros                9.22
19                                              Penha               12.96
20                                              Perus               14.02
21                                          Pinheiros                4.92
22                                           Pirituba               11.75
23                                   Santana/Tucuruvi                9.25
24                                        Santo Amaro               11.09
25                                         São Mateus               14.20
26                                         São Miguel               13.12
27                                          Sapopemba               12.95
28                                                 Sé                9.47
29                          Vila Maria/Vila Guilherme               14.40
30                                       Vila Mariana                3.00
31                                      Vila Prudente                8.08
32                                           Ignorado              320.00
33                                              Total               11.23
34                     Fonte:SIM/SINASC/CEInfo/SMS-SP                 NaN
35                                             Notas:                 NaN
36  1. Para tabulações de proporções, o campo refe...                 NaN
37  2. Coeficientes podem ser tabuladas por Distri...                 NaN
38  3. Coeficientes resultantes de 20 óbitos ou me...                 NaN
39  Fonte: https://www.health.ny.gov/diseases/chro...                 NaN
40  4. Não recomendamos utilizar os coeficientes d...                 NaN

Novamente, vamos remover as linhas de totalização e informações adicionais.

In [8]:
df_infantil_24 = df_infantil_24[:-8]
df_infantil_24

          Subprefeitura resid  Coef_mort_infantil
0   Aricanduva/Formosa/Carrão               11.94
1                     Butantã                8.41
2                 Campo Limpo               10.25
3           Capela do Socorro               12.97
4     Casa Verde/Cachoeirinha               11.43
5               Cidade Ademar               11.77
6           Cidade Tiradentes                9.01
7          Ermelino Matarazzo                8.26
8       Freguesia/Brasilândia               15.18
9                  Guaianases               13.96
10                   Ipiranga               10.58
11             Itaim Paulista               12.11
12                   Itaquera               12.19
13                  Jabaquara                9.37
14            Jaçanã/Tremembé               12.24
15                       Lapa                3.50
16                M'Boi Mirim               10.21
17                      Mooca               11.56
18                Parelheiros                9.22
19                      Penha               12.96
20                      Perus               14.02
21                  Pinheiros                4.92
22                   Pirituba               11.75
23           Santana/Tucuruvi                9.25
24                Santo Amaro               11.09
25                 São Mateus               14.20
26                 São Miguel               13.12
27                  Sapopemba               12.95
28                         Sé                9.47
29  Vila Maria/Vila Guilherme               14.40
30               Vila Mariana                3.00
31              Vila Prudente                8.08
32                   Ignorado              320.00

### 2025

In [9]:
file_name_obitos_infantil_25 = 'A003858192_29_141_165.csv'
df_obitos_infantil_25 = pd.read_csv(path.join(data_input_dir, file_name_obitos_infantil_25),
                                    sep=';', encoding='latin1', decimal=',', skiprows=4)
df_obitos_infantil_25 = df_obitos_infantil_25[:-6]
df_obitos_infantil_25

     Subprefeitura residência  Óbitos_Residentes_MSP
0   Aricanduva/Formosa/Carrão                   18.0
1                     Butantã                   41.0
2                 Campo Limpo                   66.0
3           Capela do Socorro                   79.0
4     Casa Verde/Cachoeirinha                   37.0
5               Cidade Ademar                   57.0
6           Cidade Tiradentes                   32.0
7          Ermelino Matarazzo                   14.0
8       Freguesia/Brasilândia                   68.0
9                  Guaianases                   37.0
10                   Ipiranga                   33.0
11             Itaim Paulista                   43.0
12                   Itaquera                   69.0
13                  Jabaquara                   16.0
14            Jaçanã/Tremembé                   51.0
15                       Lapa                   23.0
16                M'Boi Mirim                   67.0
17                      Moóca                   41.0
18                Parelheiros                   25.0
19                      Penha                   58.0
20                      Perus                   27.0
21                  Pinheiros                    4.0
22                   Pirituba                   56.0
23           Santana/Tucuruvi                   22.0
24                Santo Amaro                   14.0
25                 São Mateus                   62.0
26                 São Miguel                   47.0
27                  Sapopemba                   35.0
28                         Sé                   29.0
29  Vila Maria/Vila Guilherme                   40.0
30               Vila Mariana                    8.0
31              Vila Prudente                   17.0
32                   Ignorado                   32.0

## Nascidos Vivos

Os dados de nascidos vivos também são obtidos do TabNet.

In [10]:
file_name_nv = 'A004130192_29_141_165.csv'
df_nv = pd.read_csv(path.join(data_input_dir, file_name_nv),
                    sep=';', encoding='latin1', decimal=',', skiprows=3)
df_nv = df_nv[:-3]
df_nv

     SubPrefeitura residência    2024    2025    Total
0   Aricanduva/Formosa/Carrão  2177.0  2302.0   4479.0
1                     Butantã  4399.0  4639.0   9038.0
2                 Campo Limpo  7417.0  7368.0  14785.0
3           Capela do Socorro  7092.0  7121.0  14213.0
4     Casa Verde/Cachoeirinha  3236.0  3428.0   6664.0
5               Cidade Ademar  4673.0  4819.0   9492.0
6           Cidade Tiradentes  2552.0  2530.0   5082.0
7          Ermelino Matarazzo  2057.0  2121.0   4178.0
8       Freguesia/Brasilândia  4215.0  4293.0   8508.0
9                  Guaianases  3511.0  3400.0   6911.0
10                   Ipiranga  4633.0  4505.0   9138.0
11             Itaim Paulista  4046.0  3996.0   8042.0
12                   Itaquera  6153.0  6571.0  12724.0
13                  Jabaquara  1814.0  1871.0   3685.0
14            Jaçanã/Tremembé  3512.0  3564.0   7076.0
15                       Lapa  2861.0  2823.0   5684.0
16                M'Boi Mirim  6952.0  6815.0  13767.0
17                      Mooca  4153.0  4137.0   8290.0
18                Parelheiros  2170.0  2257.0   4427.0
19                      Penha  4628.0  4833.0   9461.0
20                      Perus  1855.0  1917.0   3772.0
21                  Pinheiros  2640.0  2778.0   5418.0
22                   Pirituba  4935.0  4815.0   9750.0
23           Santana/Tucuruvi  2594.0  2531.0   5125.0
24                Santo Amaro  2345.0  2417.0   4762.0
25                 São Mateus  5281.0  5421.0  10702.0
26                 São Miguel  4041.0  4087.0   8128.0
27                  Sapopemba  2858.0  2903.0   5761.0
28                         Sé  3696.0  3839.0   7535.0
29  Vila Maria/Vila Guilherme  3472.0  3700.0   7172.0
30               Vila Mariana  2663.0  2721.0   5384.0
31              Vila Prudente  2105.0  2237.0   4342.0
32                   Ignorado    50.0    46.0     96.0

Nesse caso, temos também que excluir a coluna de totalização.

In [11]:
df_nv = df_nv.drop(columns=['Total'])
df_nv

     SubPrefeitura residência    2024    2025
0   Aricanduva/Formosa/Carrão  2177.0  2302.0
1                     Butantã  4399.0  4639.0
2                 Campo Limpo  7417.0  7368.0
3           Capela do Socorro  7092.0  7121.0
4     Casa Verde/Cachoeirinha  3236.0  3428.0
5               Cidade Ademar  4673.0  4819.0
6           Cidade Tiradentes  2552.0  2530.0
7          Ermelino Matarazzo  2057.0  2121.0
8       Freguesia/Brasilândia  4215.0  4293.0
9                  Guaianases  3511.0  3400.0
10                   Ipiranga  4633.0  4505.0
11             Itaim Paulista  4046.0  3996.0
12                   Itaquera  6153.0  6571.0
13                  Jabaquara  1814.0  1871.0
14            Jaçanã/Tremembé  3512.0  3564.0
15                       Lapa  2861.0  2823.0
16                M'Boi Mirim  6952.0  6815.0
17                      Mooca  4153.0  4137.0
18                Parelheiros  2170.0  2257.0
19                      Penha  4628.0  4833.0
20                      Perus  1855.0  1917.0
21                  Pinheiros  2640.0  2778.0
22                   Pirituba  4935.0  4815.0
23           Santana/Tucuruvi  2594.0  2531.0
24                Santo Amaro  2345.0  2417.0
25                 São Mateus  5281.0  5421.0
26                 São Miguel  4041.0  4087.0
27                  Sapopemba  2858.0  2903.0
28                         Sé  3696.0  3839.0
29  Vila Maria/Vila Guilherme  3472.0  3700.0
30               Vila Mariana  2663.0  2721.0
31              Vila Prudente  2105.0  2237.0
32                   Ignorado    50.0    46.0

## Subprefeituras

Para que possamos unir os dados aqui e no Qlik precisamos padronizar o nome das Subprefeituras para utilizar como chave. Para isso, vamos carregar o arquivo de subprefeituras utilizado no Qlik.

In [12]:
url_subs = environ.get('CSV_SUBPREFEITURAS_QLIK')
df_subs = pd.read_csv(url_subs)
df_subs

,sub.CODIGO,sub.NOME,sub.POLIGONO,total_de_pessoas
0,1,PERUS,"[[[[-46.7082012617476,-23.4165818252815],[-46....",163076
1,2,PIRITUBA-JARAGUA,"[[[[-46.7753669019781,-23.4628032705496],[-46....",480225
2,3,FREGUESIA-BRASILANDIA,"[[[[-46.6910223492151,-23.5088410763715],[-46....",380513
3,4,CASA VERDE-CACHOEIRINHA,"[[[[-46.673577305455,-23.479858692024],[-46.67...",306275
4,5,SANTANA-TUCURUVI,"[[[[-46.6251942372966,-23.5193645522374],[-46....",318913
5,6,JACANA-TREMEMBE,"[[[[-46.6138088697146,-23.4620183373337],[-46....",283892
6,7,VILA MARIA-VILA GUILHERME,"[[[[-46.5985584306269,-23.4916579527685],[-46....",276069
7,8,LAPA,"[[[[-46.7475634318888,-23.5587659797062],[-46....",338347
8,9,SE,"[[[[-46.6634017492882,-23.5366395157441],[-46....",423536
9,10,BUTANTA,"[[[[-46.7579053376809,-23.5510466758162],[-46....",468522
10,11,PINHEIROS,"[[[[-46.6873257325884,-23.6261005948649],[-46....",285815
11,12,VILA MARIANA,"[[[[-46.6466231102846,-23.6318751226343],[-46....",337654
12,13,IPIRANGA,"[[[[-46.6144174088106,-23.5817429681912],[-46....",480878
13,14,SANTO AMARO,"[[[[-46.6871184024493,-23.6262042574839],[-46....",272308
14,15,JABAQUARA,"[[[[-46.6514911841313,-23.639281619134],[-46.6...",214982
15,16,CIDADE ADEMAR,"[[[[-46.6436598239316,-23.6711448733991],[-46....",412804
16,17,CAMPO LIMPO,"[[[[-46.7488186849265,-23.6170307889433],[-46....",675598
17,18,M BOI MIRIM,"[[[[-46.7978153624677,-23.6966712465463],[-46....",570809
18,19,CAPELA DO SOCORRO,"[[[[-46.7239680778519,-23.7003633100076],[-46....",605383
19,20,PARELHEIROS,"[[[[-46.7670823703732,-23.7542674823043],[-46....",165138
20,21,PENHA,"[[[[-46.5001019550132,-23.4772971422316],[-46....",472757
21,22,ERMELINO MATARAZZO,"[[[[-46.4777764784187,-23.5079412725303],[-46....",202214
22,23,SAO MIGUEL,"[[[[-46.4450300522138,-23.5259251812641],[-46....",344609
23,24,ITAIM PAULISTA,"[[[[-46.4064461192725,-23.5289195706913],[-46....",345968
24,25,MOOCA,"[[[[-46.6248908345177,-23.5343267292496],[-46....",377163
25,26,ARICANDUVA-FORMOSA-CARRAO,"[[[[-46.5540056763679,-23.5550942316414],[-46....",266157
26,27,ITAQUERA,"[[[[-46.4322812602783,-23.5263593067658],[-46....",550540
27,28,GUAIANASES,"[[[[-46.4234585487012,-23.5393558027579],[-46....",273707
28,29,VILA PRUDENTE,"[[[[-46.5794802013929,-23.6045586898005],[-46....",243728
29,30,SAO MATEUS,"[[[[-46.4838565669135,-23.6236721840668],[-46....",453527
30,31,CIDADE TIRADENTES,"[[[[-46.3975119128078,-23.6154254384527],[-46....",194177
31,32,SAPOPEMBA,"[[[[-46.5228118371426,-23.6138210842128],[-46....",266715

# Transformação dos dados

## Padronizando os nomes de subprefeituras

In [13]:
df_subs_qlik = df_subs['sub.NOME'].sort_values().tolist()
df_subs_qlik

['ARICANDUVA-FORMOSA-CARRAO',
 'BUTANTA',
 'CAMPO LIMPO',
 'CAPELA DO SOCORRO',
 'CASA VERDE-CACHOEIRINHA',
 'CIDADE ADEMAR',
 'CIDADE TIRADENTES',
 'ERMELINO MATARAZZO',
 'FREGUESIA-BRASILANDIA',
 'GUAIANASES',
 'IPIRANGA',
 'ITAIM PAULISTA',
 'ITAQUERA',
 'JABAQUARA',
 'JACANA-TREMEMBE',
 'LAPA',
 'M BOI MIRIM',
 'MOOCA',
 'PARELHEIROS',
 'PENHA',
 'PERUS',
 'PINHEIROS',
 'PIRITUBA-JARAGUA',
 'SANTANA-TUCURUVI',
 'SANTO AMARO',
 'SAO MATEUS',
 'SAO MIGUEL',
 'SAPOPEMBA',
 'SE',
 'VILA MARIA-VILA GUILHERME',
 'VILA MARIANA',
 'VILA PRUDENTE']

### Mortalidade Materna

In [14]:
subs_materna_24 = (
    df_materna_24[df_materna_24['nivel_regional'] == 'Subprefeitura']
    .assign(Subprefeitura=df_materna_24['região'].apply(unidecode))
    .sort_values('Subprefeitura')
    ['região']
    .tolist()
)
subs_materna_24

['Aricanduva-Formosa-Carrão',
 'Butantã',
 'Campo Limpo',
 'Capela Do Socorro',
 'Casa Verde-Cachoeirinha',
 'Cidade Ademar',
 'Cidade Tiradentes',
 'Ermelino Matarazzo',
 'Freguesia-Brasilândia',
 'Guaianases',
 'Ipiranga',
 'Itaim Paulista',
 'Itaquera',
 'Jabaquara',
 'Jaçanã-Tremembé',
 'Lapa',
 "M'Boi Mirim",
 'Mooca',
 'Parelheiros',
 'Penha',
 'Perus',
 'Pinheiros',
 'Pirituba-Jaraguá',
 'Santana-Tucuruvi',
 'Santo Amaro',
 'São Mateus',
 'São Miguel',
 'Sapopemba',
 'Sé',
 'Vila Maria-Vila Guilherme',
 'Vila Mariana',
 'Vila Prudente']

In [15]:
map_materna_24 = dict(zip(subs_materna_24, df_subs_qlik))
map_materna_24

{'Aricanduva-Formosa-Carrão': 'ARICANDUVA-FORMOSA-CARRAO',
 'Butantã': 'BUTANTA',
 'Campo Limpo': 'CAMPO LIMPO',
 'Capela Do Socorro': 'CAPELA DO SOCORRO',
 'Casa Verde-Cachoeirinha': 'CASA VERDE-CACHOEIRINHA',
 'Cidade Ademar': 'CIDADE ADEMAR',
 'Cidade Tiradentes': 'CIDADE TIRADENTES',
 'Ermelino Matarazzo': 'ERMELINO MATARAZZO',
 'Freguesia-Brasilândia': 'FREGUESIA-BRASILANDIA',
 'Guaianases': 'GUAIANASES',
 'Ipiranga': 'IPIRANGA',
 'Itaim Paulista': 'ITAIM PAULISTA',
 'Itaquera': 'ITAQUERA',
 'Jabaquara': 'JABAQUARA',
 'Jaçanã-Tremembé': 'JACANA-TREMEMBE',
 'Lapa': 'LAPA',
 "M'Boi Mirim": 'M BOI MIRIM',
 'Mooca': 'MOOCA',
 'Parelheiros': 'PARELHEIROS',
 'Penha': 'PENHA',
 'Perus': 'PERUS',
 'Pinheiros': 'PINHEIROS',
 'Pirituba-Jaraguá': 'PIRITUBA-JARAGUA',
 'Santana-Tucuruvi': 'SANTANA-TUCURUVI',
 'Santo Amaro': 'SANTO AMARO',
 'São Mateus': 'SAO MATEUS',
 'São Miguel': 'SAO MIGUEL',
 'Sapopemba': 'SAPOPEMBA',
 'Sé': 'SE',
 'Vila Maria-Vila Guilherme': 'VILA MARIA-VILA GUILHERME',
 'Vila Mariana': 'VILA MARIANA',
 'Vila Prudente': 'VILA PRUDENTE'}

In [16]:
df_materna_24['sub.NOME'] = df_materna_24['região'].map(map_materna_24)
df_materna_24

,região,nivel_regional,indicador,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,sub.NOME
0,São Paulo,Município,03.01.01 Razão de mortalidade materna (por 100...,59.5049,49.4625,49.1477,62.5654,58.4294,56.7917,59.0706,47.7766,50.4430,56.4131,65.0961,35.5896,29.5247,25.6544,NaN
1,Guaianases,Subprefeitura,03.01.01 Razão de mortalidade materna (por 100...,120.6030,39.8248,138.5864,153.6393,118.8119,59.8563,155.6723,60.9632,63.5997,45.1365,0.0000,0.0000,79.7448,56.9638,GUAIANASES
2,Ipiranga,Subprefeitura,03.01.01 Razão de mortalidade materna (por 100...,15.1883,76.4292,15.2999,30.1114,44.6163,77.9180,15.7978,15.5933,16.7898,35.6888,58.3771,0.0000,41.0256,21.5936,IPIRANGA
3,Pinheiros,Subprefeitura,03.01.01 Razão de mortalidade materna (por 100...,96.3391,32.4044,33.0251,32.4570,0.0000,34.3525,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,PINHEIROS
4,Pirituba-Jaraguá,Subprefeitura,03.01.01 Razão de mortalidade materna (por 100...,42.3430,57.6037,29.5639,43.3839,72.1605,77.1724,76.2544,31.5657,64.9351,88.9363,55.5042,56.9801,37.6152,20.3707,PIRITUBA-JARAGUA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,Vila Guilherme,Distrito,03.01.01 Razão de mortalidade materna (por 100...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,446.4286,0.0000,153.6098,0.0000,NaN
125,Vila Matilde,Distrito,03.01.01 Razão de mortalidade materna (por 100...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,203.6660,99.2063,104.4932,109.0513,NaN
126,Vila Prudente,Distrito,03.01.01 Razão de mortalidade materna (por 100...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,90.4977,0.0000,0.0000,0.0000,VILA PRUDENTE
127,Penha,Distrito,03.01.01 Razão de mortalidade materna (por 100...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,79.4913,PENHA
128,São Miguel,Distrito,03.01.01 Razão de mortalidade materna (por 100...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,95.1475,97.3710,99.2063,104.7120,SAO MIGUEL

In [17]:
subs_materna_25 = (
    df_obitos_materna_25
    .assign(Subprefeitura=df_obitos_materna_25['Subprefeitura residência'].apply(unidecode))
    .sort_values('Subprefeitura')
    ['Subprefeitura residência']
    .tolist()
)
subs_materna_25.remove('Ignorado')
subs_materna_25

['Aricanduva/Formosa/Carrão',
 'Butantã',
 'Campo Limpo',
 'Capela do Socorro',
 'Casa Verde/Cachoeirinha',
 'Cidade Ademar',
 'Cidade Tiradentes',
 'Ermelino Matarazzo',
 'Freguesia/Brasilândia',
 'Guaianases',
 'Ipiranga',
 'Itaim Paulista',
 'Itaquera',
 'Jabaquara',
 'Jaçanã/Tremembé',
 'Lapa',
 "M'Boi Mirim",
 'Mooca',
 'Parelheiros',
 'Penha',
 'Perus',
 'Pinheiros',
 'Pirituba',
 'Santana/Tucuruvi',
 'Santo Amaro',
 'São Mateus',
 'São Miguel',
 'Sapopemba',
 'Sé',
 'Vila Maria/Vila Guilherme',
 'Vila Mariana',
 'Vila Prudente']

In [18]:
map_materna_25 = dict(zip(subs_materna_25, df_subs_qlik))
map_materna_25

{'Aricanduva/Formosa/Carrão': 'ARICANDUVA-FORMOSA-CARRAO',
 'Butantã': 'BUTANTA',
 'Campo Limpo': 'CAMPO LIMPO',
 'Capela do Socorro': 'CAPELA DO SOCORRO',
 'Casa Verde/Cachoeirinha': 'CASA VERDE-CACHOEIRINHA',
 'Cidade Ademar': 'CIDADE ADEMAR',
 'Cidade Tiradentes': 'CIDADE TIRADENTES',
 'Ermelino Matarazzo': 'ERMELINO MATARAZZO',
 'Freguesia/Brasilândia': 'FREGUESIA-BRASILANDIA',
 'Guaianases': 'GUAIANASES',
 'Ipiranga': 'IPIRANGA',
 'Itaim Paulista': 'ITAIM PAULISTA',
 'Itaquera': 'ITAQUERA',
 'Jabaquara': 'JABAQUARA',
 'Jaçanã/Tremembé': 'JACANA-TREMEMBE',
 'Lapa': 'LAPA',
 "M'Boi Mirim": 'M BOI MIRIM',
 'Mooca': 'MOOCA',
 'Parelheiros': 'PARELHEIROS',
 'Penha': 'PENHA',
 'Perus': 'PERUS',
 'Pinheiros': 'PINHEIROS',
 'Pirituba': 'PIRITUBA-JARAGUA',
 'Santana/Tucuruvi': 'SANTANA-TUCURUVI',
 'Santo Amaro': 'SANTO AMARO',
 'São Mateus': 'SAO MATEUS',
 'São Miguel': 'SAO MIGUEL',
 'Sapopemba': 'SAPOPEMBA',
 'Sé': 'SE',
 'Vila Maria/Vila Guilherme': 'VILA MARIA-VILA GUILHERME',
 'Vila Mariana': 'VILA MARIANA',
 'Vila Prudente': 'VILA PRUDENTE'}

In [19]:
df_obitos_materna_25.loc[:, 'sub.NOME'] = df_obitos_materna_25['Subprefeitura residência'].map(map_materna_25)
df_obitos_materna_25

<positron-console-cell-19>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

     Subprefeitura residência Óbitos_Residentes_MSP                   sub.NOME
0   Aricanduva/Formosa/Carrão                     2  ARICANDUVA-FORMOSA-CARRAO
1                     Butantã                     1                    BUTANTA
2                 Campo Limpo                     1                CAMPO LIMPO
3           Capela do Socorro                     3          CAPELA DO SOCORRO
4     Casa Verde/Cachoeirinha                     -    CASA VERDE-CACHOEIRINHA
5               Cidade Ademar                     2              CIDADE ADEMAR
6           Cidade Tiradentes                     -          CIDADE TIRADENTES
7          Ermelino Matarazzo                     -         ERMELINO MATARAZZO
8       Freguesia/Brasilândia                     -      FREGUESIA-BRASILANDIA
9                  Guaianases                     1                 GUAIANASES
10                   Ipiranga                     2                   IPIRANGA
11             Itaim Paulista                     4             ITAIM PAULISTA
12                   Itaquera                     3                   ITAQUERA
13                  Jabaquara                     -                  JABAQUARA
14            Jaçanã/Tremembé                     3            JACANA-TREMEMBE
15                       Lapa                     -                       LAPA
16                M'Boi Mirim                     1                M BOI MIRIM
17                      Mooca                     3                      MOOCA
18                Parelheiros                     -                PARELHEIROS
19                      Penha                     2                      PENHA
20                      Perus                     2                      PERUS
21                  Pinheiros                     -                  PINHEIROS
22                   Pirituba                     2           PIRITUBA-JARAGUA
23           Santana/Tucuruvi                     1           SANTANA-TUCURUVI
24                Santo Amaro                     1                SANTO AMARO
25                 São Mateus                     3                 SAO MATEUS
26                 São Miguel                     2                 SAO MIGUEL
27                  Sapopemba                     2                  SAPOPEMBA
28                         Sé                     1                         SE
29  Vila Maria/Vila Guilherme                     3  VILA MARIA-VILA GUILHERME
30               Vila Mariana                     -               VILA MARIANA
31              Vila Prudente                     -              VILA PRUDENTE
32                   Ignorado                     1                        NaN

### Mortalidade Infantil

In [20]:
subs_infantil_24 = (
    df_infantil_24
    .assign(Subprefeitura=df_infantil_24['Subprefeitura resid'].apply(unidecode))
    .sort_values('Subprefeitura')
    ['Subprefeitura resid']
    .tolist()
)
subs_infantil_24.remove('Ignorado')
subs_infantil_24

['Aricanduva/Formosa/Carrão',
 'Butantã',
 'Campo Limpo',
 'Capela do Socorro',
 'Casa Verde/Cachoeirinha',
 'Cidade Ademar',
 'Cidade Tiradentes',
 'Ermelino Matarazzo',
 'Freguesia/Brasilândia',
 'Guaianases',
 'Ipiranga',
 'Itaim Paulista',
 'Itaquera',
 'Jabaquara',
 'Jaçanã/Tremembé',
 'Lapa',
 "M'Boi Mirim",
 'Mooca',
 'Parelheiros',
 'Penha',
 'Perus',
 'Pinheiros',
 'Pirituba',
 'Santana/Tucuruvi',
 'Santo Amaro',
 'São Mateus',
 'São Miguel',
 'Sapopemba',
 'Sé',
 'Vila Maria/Vila Guilherme',
 'Vila Mariana',
 'Vila Prudente']

In [21]:
map_infantil_24 = dict(zip(subs_infantil_24, df_subs_qlik))
map_infantil_24

{'Aricanduva/Formosa/Carrão': 'ARICANDUVA-FORMOSA-CARRAO',
 'Butantã': 'BUTANTA',
 'Campo Limpo': 'CAMPO LIMPO',
 'Capela do Socorro': 'CAPELA DO SOCORRO',
 'Casa Verde/Cachoeirinha': 'CASA VERDE-CACHOEIRINHA',
 'Cidade Ademar': 'CIDADE ADEMAR',
 'Cidade Tiradentes': 'CIDADE TIRADENTES',
 'Ermelino Matarazzo': 'ERMELINO MATARAZZO',
 'Freguesia/Brasilândia': 'FREGUESIA-BRASILANDIA',
 'Guaianases': 'GUAIANASES',
 'Ipiranga': 'IPIRANGA',
 'Itaim Paulista': 'ITAIM PAULISTA',
 'Itaquera': 'ITAQUERA',
 'Jabaquara': 'JABAQUARA',
 'Jaçanã/Tremembé': 'JACANA-TREMEMBE',
 'Lapa': 'LAPA',
 "M'Boi Mirim": 'M BOI MIRIM',
 'Mooca': 'MOOCA',
 'Parelheiros': 'PARELHEIROS',
 'Penha': 'PENHA',
 'Perus': 'PERUS',
 'Pinheiros': 'PINHEIROS',
 'Pirituba': 'PIRITUBA-JARAGUA',
 'Santana/Tucuruvi': 'SANTANA-TUCURUVI',
 'Santo Amaro': 'SANTO AMARO',
 'São Mateus': 'SAO MATEUS',
 'São Miguel': 'SAO MIGUEL',
 'Sapopemba': 'SAPOPEMBA',
 'Sé': 'SE',
 'Vila Maria/Vila Guilherme': 'VILA MARIA-VILA GUILHERME',
 'Vila Mariana': 'VILA MARIANA',
 'Vila Prudente': 'VILA PRUDENTE'}

In [22]:
df_infantil_24.loc[:, 'sub.NOME'] = df_infantil_24.loc[:, 'Subprefeitura resid'].map(map_infantil_24)
df_infantil_24

<positron-console-cell-22>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

          Subprefeitura resid  Coef_mort_infantil                   sub.NOME
0   Aricanduva/Formosa/Carrão               11.94  ARICANDUVA-FORMOSA-CARRAO
1                     Butantã                8.41                    BUTANTA
2                 Campo Limpo               10.25                CAMPO LIMPO
3           Capela do Socorro               12.97          CAPELA DO SOCORRO
4     Casa Verde/Cachoeirinha               11.43    CASA VERDE-CACHOEIRINHA
5               Cidade Ademar               11.77              CIDADE ADEMAR
6           Cidade Tiradentes                9.01          CIDADE TIRADENTES
7          Ermelino Matarazzo                8.26         ERMELINO MATARAZZO
8       Freguesia/Brasilândia               15.18      FREGUESIA-BRASILANDIA
9                  Guaianases               13.96                 GUAIANASES
10                   Ipiranga               10.58                   IPIRANGA
11             Itaim Paulista               12.11             ITAIM PAULISTA
12                   Itaquera               12.19                   ITAQUERA
13                  Jabaquara                9.37                  JABAQUARA
14            Jaçanã/Tremembé               12.24            JACANA-TREMEMBE
15                       Lapa                3.50                       LAPA
16                M'Boi Mirim               10.21                M BOI MIRIM
17                      Mooca               11.56                      MOOCA
18                Parelheiros                9.22                PARELHEIROS
19                      Penha               12.96                      PENHA
20                      Perus               14.02                      PERUS
21                  Pinheiros                4.92                  PINHEIROS
22                   Pirituba               11.75           PIRITUBA-JARAGUA
23           Santana/Tucuruvi                9.25           SANTANA-TUCURUVI
24                Santo Amaro               11.09                SANTO AMARO
25                 São Mateus               14.20                 SAO MATEUS
26                 São Miguel               13.12                 SAO MIGUEL
27                  Sapopemba               12.95                  SAPOPEMBA
28                         Sé                9.47                         SE
29  Vila Maria/Vila Guilherme               14.40  VILA MARIA-VILA GUILHERME
30               Vila Mariana                3.00               VILA MARIANA
31              Vila Prudente                8.08              VILA PRUDENTE
32                   Ignorado              320.00                        NaN

In [23]:
subs_infantil_25 = (
    df_obitos_infantil_25
    .assign(Subprefeitura=df_obitos_infantil_25['Subprefeitura residência'].apply(unidecode))
    .sort_values('Subprefeitura')
    ['Subprefeitura residência']
    .tolist()
)
subs_infantil_25.remove('Ignorado')
subs_infantil_25

['Aricanduva/Formosa/Carrão',
 'Butantã',
 'Campo Limpo',
 'Capela do Socorro',
 'Casa Verde/Cachoeirinha',
 'Cidade Ademar',
 'Cidade Tiradentes',
 'Ermelino Matarazzo',
 'Freguesia/Brasilândia',
 'Guaianases',
 'Ipiranga',
 'Itaim Paulista',
 'Itaquera',
 'Jabaquara',
 'Jaçanã/Tremembé',
 'Lapa',
 "M'Boi Mirim",
 'Moóca',
 'Parelheiros',
 'Penha',
 'Perus',
 'Pinheiros',
 'Pirituba',
 'Santana/Tucuruvi',
 'Santo Amaro',
 'São Mateus',
 'São Miguel',
 'Sapopemba',
 'Sé',
 'Vila Maria/Vila Guilherme',
 'Vila Mariana',
 'Vila Prudente']

In [24]:
map_infantil_25 = dict(zip(subs_infantil_25, df_subs_qlik))
map_infantil_25

{'Aricanduva/Formosa/Carrão': 'ARICANDUVA-FORMOSA-CARRAO',
 'Butantã': 'BUTANTA',
 'Campo Limpo': 'CAMPO LIMPO',
 'Capela do Socorro': 'CAPELA DO SOCORRO',
 'Casa Verde/Cachoeirinha': 'CASA VERDE-CACHOEIRINHA',
 'Cidade Ademar': 'CIDADE ADEMAR',
 'Cidade Tiradentes': 'CIDADE TIRADENTES',
 'Ermelino Matarazzo': 'ERMELINO MATARAZZO',
 'Freguesia/Brasilândia': 'FREGUESIA-BRASILANDIA',
 'Guaianases': 'GUAIANASES',
 'Ipiranga': 'IPIRANGA',
 'Itaim Paulista': 'ITAIM PAULISTA',
 'Itaquera': 'ITAQUERA',
 'Jabaquara': 'JABAQUARA',
 'Jaçanã/Tremembé': 'JACANA-TREMEMBE',
 'Lapa': 'LAPA',
 "M'Boi Mirim": 'M BOI MIRIM',
 'Moóca': 'MOOCA',
 'Parelheiros': 'PARELHEIROS',
 'Penha': 'PENHA',
 'Perus': 'PERUS',
 'Pinheiros': 'PINHEIROS',
 'Pirituba': 'PIRITUBA-JARAGUA',
 'Santana/Tucuruvi': 'SANTANA-TUCURUVI',
 'Santo Amaro': 'SANTO AMARO',
 'São Mateus': 'SAO MATEUS',
 'São Miguel': 'SAO MIGUEL',
 'Sapopemba': 'SAPOPEMBA',
 'Sé': 'SE',
 'Vila Maria/Vila Guilherme': 'VILA MARIA-VILA GUILHERME',
 'Vila Mariana': 'VILA MARIANA',
 'Vila Prudente': 'VILA PRUDENTE'}

In [25]:
df_obitos_infantil_25.loc[:, 'sub.NOME'] = df_obitos_infantil_25.loc[:, 'Subprefeitura residência'].map(map_infantil_25)
df_obitos_infantil_25

,Subprefeitura residência,Óbitos_Residentes_MSP,sub.NOME
0,Aricanduva/Formosa/Carrão,18.0,ARICANDUVA-FORMOSA-CARRAO
1,Butantã,41.0,BUTANTA
2,Campo Limpo,66.0,CAMPO LIMPO
3,Capela do Socorro,79.0,CAPELA DO SOCORRO
4,Casa Verde/Cachoeirinha,37.0,CASA VERDE-CACHOEIRINHA
5,Cidade Ademar,57.0,CIDADE ADEMAR
6,Cidade Tiradentes,32.0,CIDADE TIRADENTES
7,Ermelino Matarazzo,14.0,ERMELINO MATARAZZO
8,Freguesia/Brasilândia,68.0,FREGUESIA-BRASILANDIA
9,Guaianases,37.0,GUAIANASES
10,Ipiranga,33.0,IPIRANGA
11,Itaim Paulista,43.0,ITAIM PAULISTA
12,Itaquera,69.0,ITAQUERA
13,Jabaquara,16.0,JABAQUARA
14,Jaçanã/Tremembé,51.0,JACANA-TREMEMBE
15,Lapa,23.0,LAPA
16,M'Boi Mirim,67.0,M BOI MIRIM
17,Moóca,41.0,MOOCA
18,Parelheiros,25.0,PARELHEIROS
19,Penha,58.0,PENHA
20,Perus,27.0,PERUS
21,Pinheiros,4.0,PINHEIROS
22,Pirituba,56.0,PIRITUBA-JARAGUA
23,Santana/Tucuruvi,22.0,SANTANA-TUCURUVI
24,Santo Amaro,14.0,SANTO AMARO
25,São Mateus,62.0,SAO MATEUS
26,São Miguel,47.0,SAO MIGUEL
27,Sapopemba,35.0,SAPOPEMBA
28,Sé,29.0,SE
29,Vila Maria/Vila Guilherme,40.0,VILA MARIA-VILA GUILHERME
30,Vila Mariana,8.0,VILA MARIANA
31,Vila Prudente,17.0,VILA PRUDENTE
32,Ignorado,32.0,NaN

### Nascidos Vivos

In [26]:
subs_nv = (
    df_nv
    .assign(Subprefeitura=df_nv['SubPrefeitura residência'].apply(unidecode))
    .sort_values('Subprefeitura')
    ['SubPrefeitura residência']
    .tolist()
)
subs_nv.remove('Ignorado')
subs_nv

['Aricanduva/Formosa/Carrão',
 'Butantã',
 'Campo Limpo',
 'Capela do Socorro',
 'Casa Verde/Cachoeirinha',
 'Cidade Ademar',
 'Cidade Tiradentes',
 'Ermelino Matarazzo',
 'Freguesia/Brasilândia',
 'Guaianases',
 'Ipiranga',
 'Itaim Paulista',
 'Itaquera',
 'Jabaquara',
 'Jaçanã/Tremembé',
 'Lapa',
 "M'Boi Mirim",
 'Mooca',
 'Parelheiros',
 'Penha',
 'Perus',
 'Pinheiros',
 'Pirituba',
 'Santana/Tucuruvi',
 'Santo Amaro',
 'São Mateus',
 'São Miguel',
 'Sapopemba',
 'Sé',
 'Vila Maria/Vila Guilherme',
 'Vila Mariana',
 'Vila Prudente']

In [27]:
map_nv = dict(zip(subs_nv, df_subs_qlik))
map_nv

{'Aricanduva/Formosa/Carrão': 'ARICANDUVA-FORMOSA-CARRAO',
 'Butantã': 'BUTANTA',
 'Campo Limpo': 'CAMPO LIMPO',
 'Capela do Socorro': 'CAPELA DO SOCORRO',
 'Casa Verde/Cachoeirinha': 'CASA VERDE-CACHOEIRINHA',
 'Cidade Ademar': 'CIDADE ADEMAR',
 'Cidade Tiradentes': 'CIDADE TIRADENTES',
 'Ermelino Matarazzo': 'ERMELINO MATARAZZO',
 'Freguesia/Brasilândia': 'FREGUESIA-BRASILANDIA',
 'Guaianases': 'GUAIANASES',
 'Ipiranga': 'IPIRANGA',
 'Itaim Paulista': 'ITAIM PAULISTA',
 'Itaquera': 'ITAQUERA',
 'Jabaquara': 'JABAQUARA',
 'Jaçanã/Tremembé': 'JACANA-TREMEMBE',
 'Lapa': 'LAPA',
 "M'Boi Mirim": 'M BOI MIRIM',
 'Mooca': 'MOOCA',
 'Parelheiros': 'PARELHEIROS',
 'Penha': 'PENHA',
 'Perus': 'PERUS',
 'Pinheiros': 'PINHEIROS',
 'Pirituba': 'PIRITUBA-JARAGUA',
 'Santana/Tucuruvi': 'SANTANA-TUCURUVI',
 'Santo Amaro': 'SANTO AMARO',
 'São Mateus': 'SAO MATEUS',
 'São Miguel': 'SAO MIGUEL',
 'Sapopemba': 'SAPOPEMBA',
 'Sé': 'SE',
 'Vila Maria/Vila Guilherme': 'VILA MARIA-VILA GUILHERME',
 'Vila Mariana': 'VILA MARIANA',
 'Vila Prudente': 'VILA PRUDENTE'}

In [28]:
df_nv.loc[:, 'sub.NOME'] = df_nv.loc[:, 'SubPrefeitura residência'].map(map_nv)
df_nv

     SubPrefeitura residência    2024    2025                   sub.NOME
0   Aricanduva/Formosa/Carrão  2177.0  2302.0  ARICANDUVA-FORMOSA-CARRAO
1                     Butantã  4399.0  4639.0                    BUTANTA
2                 Campo Limpo  7417.0  7368.0                CAMPO LIMPO
3           Capela do Socorro  7092.0  7121.0          CAPELA DO SOCORRO
4     Casa Verde/Cachoeirinha  3236.0  3428.0    CASA VERDE-CACHOEIRINHA
5               Cidade Ademar  4673.0  4819.0              CIDADE ADEMAR
6           Cidade Tiradentes  2552.0  2530.0          CIDADE TIRADENTES
7          Ermelino Matarazzo  2057.0  2121.0         ERMELINO MATARAZZO
8       Freguesia/Brasilândia  4215.0  4293.0      FREGUESIA-BRASILANDIA
9                  Guaianases  3511.0  3400.0                 GUAIANASES
10                   Ipiranga  4633.0  4505.0                   IPIRANGA
11             Itaim Paulista  4046.0  3996.0             ITAIM PAULISTA
12                   Itaquera  6153.0  6571.0                   ITAQUERA
13                  Jabaquara  1814.0  1871.0                  JABAQUARA
14            Jaçanã/Tremembé  3512.0  3564.0            JACANA-TREMEMBE
15                       Lapa  2861.0  2823.0                       LAPA
16                M'Boi Mirim  6952.0  6815.0                M BOI MIRIM
17                      Mooca  4153.0  4137.0                      MOOCA
18                Parelheiros  2170.0  2257.0                PARELHEIROS
19                      Penha  4628.0  4833.0                      PENHA
20                      Perus  1855.0  1917.0                      PERUS
21                  Pinheiros  2640.0  2778.0                  PINHEIROS
22                   Pirituba  4935.0  4815.0           PIRITUBA-JARAGUA
23           Santana/Tucuruvi  2594.0  2531.0           SANTANA-TUCURUVI
24                Santo Amaro  2345.0  2417.0                SANTO AMARO
25                 São Mateus  5281.0  5421.0                 SAO MATEUS
26                 São Miguel  4041.0  4087.0                 SAO MIGUEL
27                  Sapopemba  2858.0  2903.0                  SAPOPEMBA
28                         Sé  3696.0  3839.0                         SE
29  Vila Maria/Vila Guilherme  3472.0  3700.0  VILA MARIA-VILA GUILHERME
30               Vila Mariana  2663.0  2721.0               VILA MARIANA
31              Vila Prudente  2105.0  2237.0              VILA PRUDENTE
32                   Ignorado    50.0    46.0                        NaN

## Mortalidade Materna

Primeiro, vamos manter apenas o nível de subprefeitura e ano de 2024 para os dados vindos do ObservaSampa.

In [29]:
df_materna_24 = df_materna_24[df_materna_24['nivel_regional'] == 'Subprefeitura']
df_materna_24 = df_materna_24[['região', 'sub.NOME', '2024']]
df_materna_24 = df_materna_24.rename(columns={'região': 'Subprefeitura'})
df_materna_24

                Subprefeitura                   sub.NOME     2024
1                  Guaianases                 GUAIANASES  56.9638
2                    Ipiranga                   IPIRANGA  21.5936
3                   Pinheiros                  PINHEIROS   0.0000
4            Pirituba-Jaraguá           PIRITUBA-JARAGUA  20.3707
5               Cidade Ademar              CIDADE ADEMAR  21.4087
6                       Penha                      PENHA  64.8508
7                       Perus                      PERUS   0.0000
8            Santana-Tucuruvi           SANTANA-TUCURUVI   0.0000
9             Jaçanã-Tremembé            JACANA-TREMEMBE  56.9638
10               Vila Mariana               VILA MARIANA   0.0000
11  Vila Maria-Vila Guilherme  VILA MARIA-VILA GUILHERME  28.8351
12  Aricanduva-Formosa-Carrão  ARICANDUVA-FORMOSA-CARRAO   0.0000
13         Ermelino Matarazzo         ERMELINO MATARAZZO  48.6145
14                    Butantã                    BUTANTA  22.7687
15                Campo Limpo                CAMPO LIMPO  13.4916
16          Cidade Tiradentes          CIDADE TIRADENTES  39.2003
17      Freguesia-Brasilândia      FREGUESIA-BRASILANDIA  23.7925
18             Itaim Paulista             ITAIM PAULISTA  24.7219
19                       Lapa                       LAPA  35.0631
20                M'Boi Mirim                M BOI MIRIM  14.3906
21                      Mooca                      MOOCA  48.1696
22                Parelheiros                PARELHEIROS   0.0000
23                Santo Amaro                SANTO AMARO  42.6621
24                  Sapopemba                  SAPOPEMBA  35.0263
25                 São Mateus                 SAO MATEUS   0.0000
26                 São Miguel                 SAO MIGUEL  74.2574
27                   Itaquera                   ITAQUERA  16.2628
28                  Jabaquara                  JABAQUARA   0.0000
29    Casa Verde-Cachoeirinha    CASA VERDE-CACHOEIRINHA  61.9195
30              Vila Prudente              VILA PRUDENTE   0.0000
31          Capela Do Socorro          CAPELA DO SOCORRO  14.1123
32                         Sé                         SE  27.0783

Agora, vamos transformar o ano em uma coluna.

In [30]:
df_materna_24 = pd.melt(df_materna_24,
                        id_vars=['Subprefeitura', 'sub.NOME'],
                        var_name='Ano',
                        value_name='Razão de mortalidade materna')
df_materna_24

,Subprefeitura,sub.NOME,Ano,Razão de mortalidade materna
0,Guaianases,GUAIANASES,2024,56.9638
1,Ipiranga,IPIRANGA,2024,21.5936
2,Pinheiros,PINHEIROS,2024,0.0000
3,Pirituba-Jaraguá,PIRITUBA-JARAGUA,2024,20.3707
4,Cidade Ademar,CIDADE ADEMAR,2024,21.4087
5,Penha,PENHA,2024,64.8508
6,Perus,PERUS,2024,0.0000
7,Santana-Tucuruvi,SANTANA-TUCURUVI,2024,0.0000
8,Jaçanã-Tremembé,JACANA-TREMEMBE,2024,56.9638
9,Vila Mariana,VILA MARIANA,2024,0.0000
10,Vila Maria-Vila Guilherme,VILA MARIA-VILA GUILHERME,2024,28.8351
11,Aricanduva-Formosa-Carrão,ARICANDUVA-FORMOSA-CARRAO,2024,0.0000
12,Ermelino Matarazzo,ERMELINO MATARAZZO,2024,48.6145
13,Butantã,BUTANTA,2024,22.7687
14,Campo Limpo,CAMPO LIMPO,2024,13.4916
15,Cidade Tiradentes,CIDADE TIRADENTES,2024,39.2003
16,Freguesia-Brasilândia,FREGUESIA-BRASILANDIA,2024,23.7925
17,Itaim Paulista,ITAIM PAULISTA,2024,24.7219
18,Lapa,LAPA,2024,35.0631
19,M'Boi Mirim,M BOI MIRIM,2024,14.3906
20,Mooca,MOOCA,2024,48.1696
21,Parelheiros,PARELHEIROS,2024,0.0000
22,Santo Amaro,SANTO AMARO,2024,42.6621
23,Sapopemba,SAPOPEMBA,2024,35.0263
24,São Mateus,SAO MATEUS,2024,0.0000
25,São Miguel,SAO MIGUEL,2024,74.2574
26,Itaquera,ITAQUERA,2024,16.2628
27,Jabaquara,JABAQUARA,2024,0.0000
28,Casa Verde-Cachoeirinha,CASA VERDE-CACHOEIRINHA,2024,61.9195
29,Vila Prudente,VILA PRUDENTE,2024,0.0000
30,Capela Do Socorro,CAPELA DO SOCORRO,2024,14.1123
31,Sé,SE,2024,27.0783

Agora, vamos adicionar a coluna de nascidos vivos para poder calcular o coeficiente.

In [31]:
df_nv  = pd.melt(df_nv,
                 id_vars=['SubPrefeitura residência', 'sub.NOME'],
                 var_name='Ano',
                 value_name='Número de nascidos vivos')
df_nv

,SubPrefeitura residência,sub.NOME,Ano,Número de nascidos vivos
0,Aricanduva/Formosa/Carrão,ARICANDUVA-FORMOSA-CARRAO,2024,2177.0
1,Butantã,BUTANTA,2024,4399.0
2,Campo Limpo,CAMPO LIMPO,2024,7417.0
3,Capela do Socorro,CAPELA DO SOCORRO,2024,7092.0
4,Casa Verde/Cachoeirinha,CASA VERDE-CACHOEIRINHA,2024,3236.0
...,...,...,...,...
61,Sé,SE,2025,3839.0
62,Vila Maria/Vila Guilherme,VILA MARIA-VILA GUILHERME,2025,3700.0
63,Vila Mariana,VILA MARIANA,2025,2721.0
64,Vila Prudente,VILA PRUDENTE,2025,2237.0
65,Ignorado,NaN,2025,46.0

In [32]:
df_materna = df_materna_24.merge(
    df_nv[['sub.NOME', 'Ano', 'Número de nascidos vivos']],
    how='left',
    left_on=['sub.NOME', 'Ano'],
    right_on=['sub.NOME', 'Ano']
)
df_materna

,Subprefeitura,sub.NOME,Ano,Razão de mortalidade materna,Número de nascidos vivos
0,Guaianases,GUAIANASES,2024,56.9638,3511.0
1,Ipiranga,IPIRANGA,2024,21.5936,4633.0
2,Pinheiros,PINHEIROS,2024,0.0000,2640.0
3,Pirituba-Jaraguá,PIRITUBA-JARAGUA,2024,20.3707,4935.0
4,Cidade Ademar,CIDADE ADEMAR,2024,21.4087,4673.0
5,Penha,PENHA,2024,64.8508,4628.0
6,Perus,PERUS,2024,0.0000,1855.0
7,Santana-Tucuruvi,SANTANA-TUCURUVI,2024,0.0000,2594.0
8,Jaçanã-Tremembé,JACANA-TREMEMBE,2024,56.9638,3512.0
9,Vila Mariana,VILA MARIANA,2024,0.0000,2663.0
10,Vila Maria-Vila Guilherme,VILA MARIA-VILA GUILHERME,2024,28.8351,3472.0
11,Aricanduva-Formosa-Carrão,ARICANDUVA-FORMOSA-CARRAO,2024,0.0000,2177.0
12,Ermelino Matarazzo,ERMELINO MATARAZZO,2024,48.6145,2057.0
13,Butantã,BUTANTA,2024,22.7687,4399.0
14,Campo Limpo,CAMPO LIMPO,2024,13.4916,7417.0
15,Cidade Tiradentes,CIDADE TIRADENTES,2024,39.2003,2552.0
16,Freguesia-Brasilândia,FREGUESIA-BRASILANDIA,2024,23.7925,4215.0
17,Itaim Paulista,ITAIM PAULISTA,2024,24.7219,4046.0
18,Lapa,LAPA,2024,35.0631,2861.0
19,M'Boi Mirim,M BOI MIRIM,2024,14.3906,6952.0
20,Mooca,MOOCA,2024,48.1696,4153.0
21,Parelheiros,PARELHEIROS,2024,0.0000,2170.0
22,Santo Amaro,SANTO AMARO,2024,42.6621,2345.0
23,Sapopemba,SAPOPEMBA,2024,35.0263,2858.0
24,São Mateus,SAO MATEUS,2024,0.0000,5281.0
25,São Miguel,SAO MIGUEL,2024,74.2574,4041.0
26,Itaquera,ITAQUERA,2024,16.2628,6153.0
27,Jabaquara,JABAQUARA,2024,0.0000,1814.0
28,Casa Verde-Cachoeirinha,CASA VERDE-CACHOEIRINHA,2024,61.9195,3236.0
29,Vila Prudente,VILA PRUDENTE,2024,0.0000,2105.0
30,Capela Do Socorro,CAPELA DO SOCORRO,2024,14.1123,7092.0
31,Sé,SE,2024,27.0783,3696.0

In [33]:
df_materna['Óbitos_Residentes_MSP'] = df_materna['Razão de mortalidade materna'] * df_materna['Número de nascidos vivos'] / 100000
df_materna = df_materna.sort_values(['sub.NOME', 'Ano']).reset_index(drop=True)
df_materna

,Subprefeitura,sub.NOME,Ano,Razão de mortalidade materna,Número de nascidos vivos,Óbitos_Residentes_MSP
0,Aricanduva-Formosa-Carrão,ARICANDUVA-FORMOSA-CARRAO,2024,0.0000,2177.0,0.000000
1,Butantã,BUTANTA,2024,22.7687,4399.0,1.001595
2,Campo Limpo,CAMPO LIMPO,2024,13.4916,7417.0,1.000672
3,Capela Do Socorro,CAPELA DO SOCORRO,2024,14.1123,7092.0,1.000844
4,Casa Verde-Cachoeirinha,CASA VERDE-CACHOEIRINHA,2024,61.9195,3236.0,2.003715
5,Cidade Ademar,CIDADE ADEMAR,2024,21.4087,4673.0,1.000429
6,Cidade Tiradentes,CIDADE TIRADENTES,2024,39.2003,2552.0,1.000392
7,Ermelino Matarazzo,ERMELINO MATARAZZO,2024,48.6145,2057.0,1.000000
8,Freguesia-Brasilândia,FREGUESIA-BRASILANDIA,2024,23.7925,4215.0,1.002854
9,Guaianases,GUAIANASES,2024,56.9638,3511.0,1.999999
10,Ipiranga,IPIRANGA,2024,21.5936,4633.0,1.000431
11,Itaim Paulista,ITAIM PAULISTA,2024,24.7219,4046.0,1.000248
12,Itaquera,ITAQUERA,2024,16.2628,6153.0,1.000650
13,Jabaquara,JABAQUARA,2024,0.0000,1814.0,0.000000
14,Jaçanã-Tremembé,JACANA-TREMEMBE,2024,56.9638,3512.0,2.000569
15,Lapa,LAPA,2024,35.0631,2861.0,1.003155
16,M'Boi Mirim,M BOI MIRIM,2024,14.3906,6952.0,1.000435
17,Mooca,MOOCA,2024,48.1696,4153.0,2.000483
18,Parelheiros,PARELHEIROS,2024,0.0000,2170.0,0.000000
19,Penha,PENHA,2024,64.8508,4628.0,3.001295
20,Perus,PERUS,2024,0.0000,1855.0,0.000000
21,Pinheiros,PINHEIROS,2024,0.0000,2640.0,0.000000
22,Pirituba-Jaraguá,PIRITUBA-JARAGUA,2024,20.3707,4935.0,1.005294
23,Santana-Tucuruvi,SANTANA-TUCURUVI,2024,0.0000,2594.0,0.000000
24,Santo Amaro,SANTO AMARO,2024,42.6621,2345.0,1.000426
25,São Mateus,SAO MATEUS,2024,0.0000,5281.0,0.000000
26,São Miguel,SAO MIGUEL,2024,74.2574,4041.0,3.000742
27,Sapopemba,SAPOPEMBA,2024,35.0263,2858.0,1.001052
28,Sé,SE,2024,27.0783,3696.0,1.000814
29,Vila Maria-Vila Guilherme,VILA MARIA-VILA GUILHERME,2024,28.8351,3472.0,1.001155
30,Vila Mariana,VILA MARIANA,2024,0.0000,2663.0,0.000000
31,Vila Prudente,VILA PRUDENTE,2024,0.0000,2105.0,0.000000

In [34]:
df_materna_25 = (
    df_obitos_materna_25
    .loc[:, ['sub.NOME', 'Óbitos_Residentes_MSP']]
    .assign(Ano='2025')
    .merge(
        df_nv[['sub.NOME', 'Ano', 'Número de nascidos vivos']],
        how='left',
        left_on=['sub.NOME', 'Ano'],
        right_on=['sub.NOME', 'Ano']
    )
)
df_materna_25

,sub.NOME,Óbitos_Residentes_MSP,Ano,Número de nascidos vivos
0,ARICANDUVA-FORMOSA-CARRAO,2,2025,2302.0
1,BUTANTA,1,2025,4639.0
2,CAMPO LIMPO,1,2025,7368.0
3,CAPELA DO SOCORRO,3,2025,7121.0
4,CASA VERDE-CACHOEIRINHA,-,2025,3428.0
5,CIDADE ADEMAR,2,2025,4819.0
6,CIDADE TIRADENTES,-,2025,2530.0
7,ERMELINO MATARAZZO,-,2025,2121.0
8,FREGUESIA-BRASILANDIA,-,2025,4293.0
9,GUAIANASES,1,2025,3400.0
10,IPIRANGA,2,2025,4505.0
11,ITAIM PAULISTA,4,2025,3996.0
12,ITAQUERA,3,2025,6571.0
13,JABAQUARA,-,2025,1871.0
14,JACANA-TREMEMBE,3,2025,3564.0
15,LAPA,-,2025,2823.0
16,M BOI MIRIM,1,2025,6815.0
17,MOOCA,3,2025,4137.0
18,PARELHEIROS,-,2025,2257.0
19,PENHA,2,2025,4833.0
20,PERUS,2,2025,1917.0
21,PINHEIROS,-,2025,2778.0
22,PIRITUBA-JARAGUA,2,2025,4815.0
23,SANTANA-TUCURUVI,1,2025,2531.0
24,SANTO AMARO,1,2025,2417.0
25,SAO MATEUS,3,2025,5421.0
26,SAO MIGUEL,2,2025,4087.0
27,SAPOPEMBA,2,2025,2903.0
28,SE,1,2025,3839.0
29,VILA MARIA-VILA GUILHERME,3,2025,3700.0
30,VILA MARIANA,-,2025,2721.0
31,VILA PRUDENTE,-,2025,2237.0
32,NaN,1,2025,46.0

In [35]:
df_materna_25['Óbitos_Residentes_MSP'] = df_materna_25['Óbitos_Residentes_MSP'].str.replace('-', '0')
df_materna_25['Óbitos_Residentes_MSP'] = df_materna_25['Óbitos_Residentes_MSP'].astype(float)
df_materna_25

,sub.NOME,Óbitos_Residentes_MSP,Ano,Número de nascidos vivos
0,ARICANDUVA-FORMOSA-CARRAO,2.0,2025,2302.0
1,BUTANTA,1.0,2025,4639.0
2,CAMPO LIMPO,1.0,2025,7368.0
3,CAPELA DO SOCORRO,3.0,2025,7121.0
4,CASA VERDE-CACHOEIRINHA,0.0,2025,3428.0
5,CIDADE ADEMAR,2.0,2025,4819.0
6,CIDADE TIRADENTES,0.0,2025,2530.0
7,ERMELINO MATARAZZO,0.0,2025,2121.0
8,FREGUESIA-BRASILANDIA,0.0,2025,4293.0
9,GUAIANASES,1.0,2025,3400.0
10,IPIRANGA,2.0,2025,4505.0
11,ITAIM PAULISTA,4.0,2025,3996.0
12,ITAQUERA,3.0,2025,6571.0
13,JABAQUARA,0.0,2025,1871.0
14,JACANA-TREMEMBE,3.0,2025,3564.0
15,LAPA,0.0,2025,2823.0
16,M BOI MIRIM,1.0,2025,6815.0
17,MOOCA,3.0,2025,4137.0
18,PARELHEIROS,0.0,2025,2257.0
19,PENHA,2.0,2025,4833.0
20,PERUS,2.0,2025,1917.0
21,PINHEIROS,0.0,2025,2778.0
22,PIRITUBA-JARAGUA,2.0,2025,4815.0
23,SANTANA-TUCURUVI,1.0,2025,2531.0
24,SANTO AMARO,1.0,2025,2417.0
25,SAO MATEUS,3.0,2025,5421.0
26,SAO MIGUEL,2.0,2025,4087.0
27,SAPOPEMBA,2.0,2025,2903.0
28,SE,1.0,2025,3839.0
29,VILA MARIA-VILA GUILHERME,3.0,2025,3700.0
30,VILA MARIANA,0.0,2025,2721.0
31,VILA PRUDENTE,0.0,2025,2237.0
32,NaN,1.0,2025,46.0

In [36]:
df_materna_25['Razão de mortalidade materna'] = df_materna_25['Óbitos_Residentes_MSP'] / df_materna_25['Número de nascidos vivos'] * 100000
df_materna_25

,sub.NOME,Óbitos_Residentes_MSP,Ano,Número de nascidos vivos,Razão de mortalidade materna
0,ARICANDUVA-FORMOSA-CARRAO,2.0,2025,2302.0,86.880973
1,BUTANTA,1.0,2025,4639.0,21.556370
2,CAMPO LIMPO,1.0,2025,7368.0,13.572204
3,CAPELA DO SOCORRO,3.0,2025,7121.0,42.128914
4,CASA VERDE-CACHOEIRINHA,0.0,2025,3428.0,0.000000
5,CIDADE ADEMAR,2.0,2025,4819.0,41.502386
6,CIDADE TIRADENTES,0.0,2025,2530.0,0.000000
7,ERMELINO MATARAZZO,0.0,2025,2121.0,0.000000
8,FREGUESIA-BRASILANDIA,0.0,2025,4293.0,0.000000
9,GUAIANASES,1.0,2025,3400.0,29.411765
10,IPIRANGA,2.0,2025,4505.0,44.395117
11,ITAIM PAULISTA,4.0,2025,3996.0,100.100100
12,ITAQUERA,3.0,2025,6571.0,45.655151
13,JABAQUARA,0.0,2025,1871.0,0.000000
14,JACANA-TREMEMBE,3.0,2025,3564.0,84.175084
15,LAPA,0.0,2025,2823.0,0.000000
16,M BOI MIRIM,1.0,2025,6815.0,14.673514
17,MOOCA,3.0,2025,4137.0,72.516316
18,PARELHEIROS,0.0,2025,2257.0,0.000000
19,PENHA,2.0,2025,4833.0,41.382164
20,PERUS,2.0,2025,1917.0,104.329682
21,PINHEIROS,0.0,2025,2778.0,0.000000
22,PIRITUBA-JARAGUA,2.0,2025,4815.0,41.536864
23,SANTANA-TUCURUVI,1.0,2025,2531.0,39.510075
24,SANTO AMARO,1.0,2025,2417.0,41.373604
25,SAO MATEUS,3.0,2025,5421.0,55.340343
26,SAO MIGUEL,2.0,2025,4087.0,48.935650
27,SAPOPEMBA,2.0,2025,2903.0,68.894247
28,SE,1.0,2025,3839.0,26.048450
29,VILA MARIA-VILA GUILHERME,3.0,2025,3700.0,81.081081
30,VILA MARIANA,0.0,2025,2721.0,0.000000
31,VILA PRUDENTE,0.0,2025,2237.0,0.000000
32,NaN,1.0,2025,46.0,2173.913043

In [37]:
df_materna = pd.concat([df_materna, df_materna_25], ignore_index=True)
df_materna = df_materna.drop(columns=['Subprefeitura'])
df_materna

,sub.NOME,Ano,Razão de mortalidade materna,Número de nascidos vivos,Óbitos_Residentes_MSP
0,ARICANDUVA-FORMOSA-CARRAO,2024,0.000000,2177.0,0.000000
1,BUTANTA,2024,22.768700,4399.0,1.001595
2,CAMPO LIMPO,2024,13.491600,7417.0,1.000672
3,CAPELA DO SOCORRO,2024,14.112300,7092.0,1.000844
4,CASA VERDE-CACHOEIRINHA,2024,61.919500,3236.0,2.003715
...,...,...,...,...,...
60,SE,2025,26.048450,3839.0,1.000000
61,VILA MARIA-VILA GUILHERME,2025,81.081081,3700.0,3.000000
62,VILA MARIANA,2025,0.000000,2721.0,0.000000
63,VILA PRUDENTE,2025,0.000000,2237.0,0.000000
64,NaN,2025,2173.913043,46.0,1.000000